apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
    template:
      metadata:
        labels:
          app: flask-api
      spec:
        containers:
        - name: flask-api
          image: {{IMAGE}}
          ports:
          - containerPort: 5000
          envFrom:
          - configMapRef:
              name: flask-api-config
          - secretRef:
              name: flask-api-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /users
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /users
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20