# Generated by Django 2.1.7 on 2019-08-05 00:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=50)),
                ('candidate_date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'candidate',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer_name', models.CharField(max_length=50)),
                ('interview_date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'interviewer',
                'managed': True,
            },
        ),
    ]
